openapi: 3.0.0
info:
  title: Distillery Controller
  version: '1.0'
  contact:
    name: Jamie Witt
    url: 'https://jamiewitt.com'
    email: me@jamiewitt.com
  description: A server to control distillery functions using Phidget controllers.x
  license:
    name: MIT
servers:
  - url: 'https://localhost:3000/distillery/v1'
externalDocs:
  url: 'https://www.phidgets.com/?view=api&product_id=OUT1100_0&lang=JavaScript'
  description: Phidget API
tags:
  - name: fractional
    description: Fractional still related operations
  - name: pot
    description: Pot still related operations
  - name: history
    description: Historical data related operations
  - name: used
    description: Used operations
  - name: unused
    description: Unused operations
paths:
  '/potstills/{still-id}/potsummary':
    get:
      summary: Your GET endpoint
      tags:
        - pot
        - used
      responses:
        '200':
          description: OK
      operationId: get-distillery-v1-potsummary
      description: Get the summary for the pot
    parameters:
      - $ref: '#/components/parameters/still-id'
  '/potsills/{still-id}/potgraphdata':
    get:
      summary: get pot graph data
      tags:
        - pot
        - used
      responses:
        '200':
          description: OK
      operationId: get-potgraphdata
      description: something
    parameters:
      - $ref: '#/components/parameters/still-id'
  /history/historicaldata:
    get:
      summary: get historical data
      tags:
        - history
        - used
      responses:
        '200':
          description: OK
      operationId: get-historicaldata
      description: something
    parameters: []
  '/history/historicaldata/{batch-id}':
    parameters:
      - schema:
          type: string
        name: batch-id
        in: path
        required: true
        description: The ID of the batch to retrieve
    get:
      summary: get historical data by id
      tags:
        - history
        - used
      responses:
        '200':
          description: OK
      operationId: get-historicaldata-batch-id
      description: something
  /history/rundata:
    get:
      summary: get run data
      tags:
        - history
        - used
      responses:
        '200':
          description: OK
      operationId: get-rundata
      description: something
    parameters: []
  '/history/rundata/{batch-id}':
    parameters:
      - schema:
          type: string
        name: batch-id
        in: path
        required: true
    get:
      summary: get run data by id
      tags:
        - history
        - unused
      responses:
        '200':
          description: OK
      operationId: get-rundata-batch-id
      description: something
    post:
      summary: update run data by id
      tags:
        - history
        - used
      responses:
        '200':
          description: OK
      operationId: post-rundata-batch-id
      description: something
  '/potstills/{still-id}/getpotcolumntemperature':
    get:
      summary: get pot temperature
      tags:
        - pot
        - unused
      responses:
        '200':
          description: OK
      operationId: get-getpotcolumntemperature
      description: something
    parameters:
      - $ref: '#/components/parameters/still-id'
  '/potstills/{still-id}/startpottemperaturelogging':
    get:
      summary: start pot temp logging
      tags:
        - pot
        - unused
      responses:
        '200':
          description: OK
      operationId: get-startpottemperaturelogging
      description: something
    parameters:
      - $ref: '#/components/parameters/still-id'
  '/potstills/{still-id}/stoppottemperaturelogging':
    get:
      summary: stop pot temp logging
      tags:
        - pot
        - unused
      responses:
        '200':
          description: OK
      operationId: get-stoppottemperaturelogging
      description: something
    parameters:
      - $ref: '#/components/parameters/still-id'
  '/potstills/{still-id}/potheaton':
    get:
      summary: pot heat on
      tags:
        - pot
        - unused
      responses:
        '200':
          description: OK
      operationId: get-potheaton
      description: something
    parameters:
      - $ref: '#/components/parameters/still-id'
  '/potstills/{still-id}/pothighvoltageheaton':
    get:
      summary: pot high voltage
      tags:
        - pot
        - unused
      responses:
        '200':
          description: OK
      operationId: get-pothighvoltageheaton
      description: something
    parameters:
      - $ref: '#/components/parameters/still-id'
  '/potstills/{still-id}/potheatoff':
    get:
      summary: turn off pot heat
      tags:
        - pot
        - unused
      responses:
        '200':
          description: OK
      operationId: get-potheatoff
      description: something
    parameters:
      - $ref: '#/components/parameters/still-id'
  '/potstills/{still-id}/resetpotafterginrun':
    get:
      summary: reset pot
      tags:
        - pot
        - unused
      responses:
        '200':
          description: OK
      operationId: get-resetpotafterginrun
      description: something
    parameters:
      - $ref: '#/components/parameters/still-id'
  '/potstills/{still-id}/setpot':
    post:
      summary: set pot
      tags:
        - pot
        - used
      responses:
        '200':
          description: OK
      operationId: post-setpot
      description: something
    parameters:
      - $ref: '#/components/parameters/still-id'
  '/fractionalstills/{still-id}/batches':
    post:
      summary: Start a fractional still batch
      tags:
        - fractional
        - used
      responses:
        '200':
          $ref: '#/components/responses/success'
      operationId: create-fractionalstill-batch
      description: Start a still batch
    parameters:
      - $ref: '#/components/parameters/still-id'
    get:
      summary: Get all batches for a still
      operationId: get-all-fractionalstill-batches
      responses:
        '200':
          $ref: '#/components/responses/success'
      description: Get all batches for a specified fractional still
      tags:
        - fractional
  '/fractionalstills/{still-id}/batches/{batch-id}':
    parameters:
      - $ref: '#/components/parameters/still-id'
      - $ref: '#/components/parameters/batch-id'
    get:
      summary: Get a specific batch for a still
      operationId: get-fractionalstill-batch
      responses:
        '200':
          $ref: '#/components/responses/success'
      description: Get the specified batch for the specified fractional still
      tags:
        - fractional
      parameters:
        - $ref: '#/components/parameters/data-format'
  '/fractionalstills/{still-id}':
    get:
      summary: Get fractional still details
      tags:
        - fractional
        - used
      responses:
        '200':
          description: OK
      operationId: get-fractionalsummary
      description: Get the details for a specified fraction still
    parameters:
      - $ref: '#/components/parameters/still-id'
  '/fractionalstills/{still-id}/arm/{arm-action}':
    parameters:
      - schema:
          type: string
          enum:
            - retract
            - extend
        name: arm-action
        in: path
        required: true
      - $ref: '#/components/parameters/still-id'
    put:
      summary: Move the fractional still arm
      operationId: perform-arm-action
      responses:
        '200':
          description: OK
      description: Extend or retract the arm
      tags:
        - fractional
  '/fractionalstills/{still-id}/heat':
    get:
      summary: Get heating element status
      tags:
        - fractional
        - unused
      responses:
        '200':
          description: OK
      operationId: get-heat-status
      description: Get the status of the heating element
    parameters:
      - $ref: '#/components/parameters/still-id'
  '/fractionalstills/{still-id}/temperature':
    get:
      summary: Get the still temperature
      tags:
        - fractional
        - unused
      responses:
        '200':
          description: OK
      operationId: get-temperature
      description: Get the current still temperature
    parameters:
      - $ref: '#/components/parameters/still-id'
  '/fractionalstills/{still-id}/valve/{valve-action}':
    parameters:
      - schema:
          type: string
          enum:
            - open
            - close
        name: valve-action
        in: path
        required: true
        description: 'The action to perform, either open or close'
      - $ref: '#/components/parameters/still-id'
    put:
      summary: Change the valve state
      operationId: perform-valve-action
      responses:
        '200':
          description: OK
      description: Open or close the valve
      tags:
        - fractional
  '/potstills/{still-id}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/success'
      operationId: get-pot
      description: Get the details of a pot still
    parameters:
      - $ref: '#/components/parameters/still-id'
  /potstills:
    parameters: []
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/success'
      operationId: get-pots-pot_id
      description: Retrieve a list of all pot stills
  /fractionalstills:
    get:
      summary: Get all of the fractional stills
      description: List of all fractional stills
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/success'
      operationId: get-fractionals
    parameters: []
  /stills:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/success'
      operationId: get-stills
      description: List all of the available stills
      parameters:
        - schema:
            type: string
          in: query
          name: type
          description: 'The type of still to retrieve, it not specified all stills will be returned'
    parameters: []
  '/fractionalstills/{still-id}/batches/active':
    parameters:
      - $ref: '#/components/parameters/still-id'
    get:
      summary: Get the active batch
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/success'
      operationId: get-active-fractionalstill-batch
      description: Convinence method to get the active batch for a specified fracational still
      parameters:
        - $ref: '#/components/parameters/data-format'
    delete:
      summary: Cancel the active batch
      operationId: cancel-fractional-still-batch
      responses:
        '200':
          description: OK
      description: Cancel the active fractional still batch
  '/fractionalstills/{still-id}/heat/{new-state}':
    parameters:
      - $ref: '#/components/parameters/still-id'
      - $ref: '#/components/parameters/new-state'
    put:
      summary: Change the heating element state
      operationId: set-heating-element-state
      responses:
        '200':
          $ref: '#/components/responses/success'
      description: Set the heating element state
      tags:
        - fractional
  '/fractionalstills/{still-id}/valve':
    parameters:
      - $ref: '#/components/parameters/still-id'
    get:
      summary: Get the valve status
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/success'
      operationId: get-valve-status
      description: Get the status of the valve
components:
  schemas: {}
  securitySchemes:
    x-client-key:
      type: apiKey
      in: header
      description: ''
      name: Application Client Key
  parameters:
    batch-id:
      name: batch-id
      in: path
      required: true
      schema:
        type: string
      description: The ID of the batch run
    still-id:
      name: still-id
      in: path
      required: true
      schema:
        type: string
      description: The ID of the still on which to operate
    data-format:
      name: data-format
      in: query
      required: false
      schema:
        type: string
        enum:
          - graph
      description: The format to return the data
    new-state:
      name: new-state
      in: path
      required: true
      schema:
        type: boolean
      description: The desired phidget state
  responses:
    success:
      description: Example response
      content:
        application/json:
          schema:
            properties:
              id:
                type: string
          examples:
            example-1:
              value:
                id: string
    not-found:
      description: Example response
      content:
        application/json:
          schema:
            properties:
              id:
                type: string
    general-error:
      description: Example response
      content:
        application/json:
          schema:
            properties:
              id:
                type: string
          examples:
            example-1:
              value:
                id: string
        application/xml:
          schema:
            type: object
            properties: {}
